
# workflow to test sverto

on:
  # is a daily check possible? i need to check the update time
  # schedule:
  #   - cron: '0 0 16 * *'
  workflow_dispatch:
    inputs:
      overwrite:
        description: "If true, overwrite existing observations. Default to false (add new obs only)."
        type: boolean
        default: false

name: Ingest monthly temperatures

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      # - uses: r-lib/actions/setup-pandoc@v2

      - name: Install Linux system dependencies
        run: |
          sudo apt update
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libssl-dev
          sudo apt install nco  
        # sudo apt install cdo
      
      - name: Restore packages with renv
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      # sets env.MONTHLY_IS_STALE=TRUE if new obs are available
      - name: Check if update is required
        id: check-update
        run: analysis-oceantemps/check-monthly.r
        shell: Rscript {0}
      
      # analysis sets env.MONTHLY_UPDATED=true and end.MONTHLY_UPDATE_TIME=...
      # when it successfully runs

      - name: Run the analysis (scheduled update)
        if: github.event_name == 'schedule' && env.MONTHLY_IS_STALE
        run: analysis-oceantemps/ingest-monthly.r --overwrite=true
        shell: Rscript {0}

      - name: Run the analysis (manual)
        if: env.MONTHLY_IS_STALE || inputs.overwrite
        run: |
          analysis-oceantemps/ingest-monthly.r \
            --overwrite=${{ inputs.overwrite }}
        shell: Rscript {0}
      
      # commit and push
      - name: Commit and push updated results
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/ocean-temps/*
          git commit -m "Ingest new results via GitHub Actions"
          git push origin main

      - name: Update Slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "event_type": ${{ github.event_name }},
              "run_end": ${{ end.MONTHLY_RUN_END }}
              "outcome_emoji":
                ${{ env.MONTHLY_IS_STALE ? '⏰' : env.MONTHLY_UPDATED ? '✅' : '❓' }},
              "outcome_long": ${{ env.MONTHLY_IS_STALE ? 'Update skipped (no new obs)' : env.MONTHLY_UPDATED ? 'New observations ingested up to ' + env.MONTHLY_UPDATE_TIME : 'Workflow successfully executed, but R script did not sign off properly. Needs follow up. ' }}
              "workflow_name": "Ocean data tracker: ingest-monthly"
            }
