
# workflow to test sverto

on:
  # is a daily check possible? i need to check the update time
  # schedule:
  #   - cron: '0 0 16 * *'
  workflow_dispatch:
    inputs:
      overwrite:
        description: "If true, overwrite existing observations. Default to false (add new obs only)."
        type: boolean
        default: false

name: Ingest monthly temperatures

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      # - uses: r-lib/actions/setup-pandoc@v2

      - name: Install Linux system dependencies
        run: |
          sudo apt update
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libssl-dev
          sudo apt install nco  
        # sudo apt install cdo
      
      - name: Restore packages with renv
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      # this script returns TRUE/FALSE - i need to set-output from that
      - name: Check if update is required
        id: check-update
        run: analysis-oceantemps/check-monthly.r
        shell: Rscript {0}
      
      - name: Run the analysis (scheduled update)
        if: github.event_name == 'schedule' && steps.check-update.outputs.stale
        run: |
          analysis-oceantemps/ingest-monthly.r \
            --overwrite=true
        shell: Rscript {0}

      - name: Run the analysis (manual)
        run: |
          analysis-oceantemps/ingest-monthly.r \
            --overwrite=${{ inputs.overwrite }}
        shell: Rscript {0}
      
      # commit and push
      - name: Commit and push updated results
        run: |
          git add data/ocean-temps/*
          git commit -m "Ingest new results via GitHub Actions"
          git push origin main
